version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQARuntimeTestprod383963Project
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: "072026"
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_OracleNonSSL
  packages:
  - name: SIQARuntimeTestprod383963Project
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
  - name: SIQACloudStreamsTests
    version: "1.0"
configurationVariables:
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.user
  : SIQA_BVT01
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.keyStore
  : ""
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.trustStore
  : ""
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.portNumber
  : "1521"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.password
  : "{AES}4eigcgUNJNC1z2PQaWS0XA=="
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.dbType
  : ORACLE
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.databaseName
  : ORCL
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionEnabled
  : "false"
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionSettings.serverName
  : adapter-oracle-121-on-amazonrds.cdmjexwbzoym.us-east-1.rds.amazonaws.com
  ? artConnection.SIQARuntimeTestprod383963Project.project.siqaruntimetestprod383963.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_OracleNonSSL.connectionManagerSettings.minimumPoolSize
  : "1"
